[package]
name = "futures-example-imperative"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
futures = { workspace = true, default-features = true, features = ["thread-pool"] }

[lints]
workspace = true
